//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamation.TimeSeries.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1977 2001 2005")]
        public string UserWaterYears {
            get {
                return ((string)(this["UserWaterYears"]));
            }
            set {
                this["UserWaterYears"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Red</string>\r\n  <string>Green</string>\r\n  <string>Blue</string>\r\n  <string" +
            ">Black</string>\r\n  <string>Orange</string>\r\n  <string>Aquamarine</string>\r\n  <st" +
            "ring>DarkGreen</string>\r\n  <string>Purple</string>\r\n  <string>Aqua</string>\r\n  <" +
            "string>Bisque</string>\r\n  <string>BlanchedAlmond</string>\r\n  <string>BlueViolet<" +
            "/string>\r\n  <string>Brown</string>\r\n  <string>BurlyWood</string>\r\n  <string>Cade" +
            "tBlue</string>\r\n  <string>Chartreuse</string>\r\n  <string>Chocolate</string>\r\n  <" +
            "string>Coral</string>\r\n  <string>CornflowerBlue</string>\r\n  <string>Cornsilk</st" +
            "ring>\r\n  <string>Crimson</string>\r\n  <string>Cyan</string>\r\n  <string>DarkBlue</" +
            "string>\r\n  <string>DarkCyan</string>\r\n  <string>DarkGoldenrod</string>\r\n  <strin" +
            "g>DarkGray</string>\r\n  <string>DarkKhaki</string>\r\n  <string>DarkMagenta</string" +
            ">\r\n  <string>AntiqueWhite</string>\r\n  <string>DarkOliveGreen</string>\r\n  <string" +
            ">DarkOrange</string>\r\n  <string>DarkOrchid</string>\r\n  <string>DarkRed</string>\r" +
            "\n  <string>DarkSalmon</string>\r\n  <string>DarkSeaGreen</string>\r\n  <string>DarkS" +
            "lateBlue</string>\r\n  <string>DarkSlateGray</string>\r\n  <string>DarkTurquoise</st" +
            "ring>\r\n  <string>DarkViolet</string>\r\n  <string>DeepPink</string>\r\n  <string>Dee" +
            "pSkyBlue</string>\r\n  <string>DimGray</string>\r\n  <string>DodgerBlue</string>\r\n  " +
            "<string>Firebrick</string>\r\n  <string>FloralWhite</string>\r\n  <string>ForestGree" +
            "n</string>\r\n  <string>Fuchsia</string>\r\n  <string>Gainsboro</string>\r\n  <string>" +
            "GhostWhite</string>\r\n  <string>Gold</string>\r\n  <string>Goldenrod</string>\r\n  <s" +
            "tring>Gray</string>\r\n  <string>Green</string>\r\n  <string>GreenYellow</string>\r\n " +
            " <string>Honeydew</string>\r\n  <string>HotPink</string>\r\n  <string>IndianRed</str" +
            "ing>\r\n  <string>Indigo</string>\r\n  <string>Ivory</string>\r\n  <string>Khaki</stri" +
            "ng>\r\n  <string>Lavender</string>\r\n  <string>LavenderBlush</string>\r\n  <string>La" +
            "wnGreen</string>\r\n  <string>LemonChiffon</string>\r\n  <string>LightBlue</string>\r" +
            "\n  <string>LightCoral</string>\r\n  <string>LightCyan</string>\r\n  <string>LightGol" +
            "denrodYellow</string>\r\n  <string>LightGray</string>\r\n  <string>LightGreen</strin" +
            "g>\r\n  <string>LightPink</string>\r\n  <string>LightSalmon</string>\r\n  <string>Ligh" +
            "tSeaGreen</string>\r\n  <string>LightSkyBlue</string>\r\n  <string>LightSlateGray</s" +
            "tring>\r\n  <string>LightSteelBlue</string>\r\n  <string>LightYellow</string>\r\n  <st" +
            "ring>Lime</string>\r\n  <string>LimeGreen</string>\r\n  <string>Linen</string>\r\n  <s" +
            "tring>Magenta</string>\r\n  <string>Maroon</string>\r\n  <string>MediumAquamarine</s" +
            "tring>\r\n  <string>MediumBlue</string>\r\n  <string>MediumOrchid</string>\r\n  <strin" +
            "g>MediumPurple</string>\r\n  <string>MediumSeaGreen</string>\r\n  <string>MediumSlat" +
            "eBlue</string>\r\n  <string>MediumSpringGreen</string>\r\n  <string>MediumTurquoise<" +
            "/string>\r\n  <string>MediumVioletRed</string>\r\n  <string>MidnightBlue</string>\r\n " +
            " <string>MintCream</string>\r\n  <string>MistyRose</string>\r\n  <string>Moccasin</s" +
            "tring>\r\n  <string>NavajoWhite</string>\r\n  <string>Navy</string>\r\n  <string>OldLa" +
            "ce</string>\r\n  <string>Olive</string>\r\n  <string>OliveDrab</string>\r\n  <string>O" +
            "rangeRed</string>\r\n  <string>Orchid</string>\r\n  <string>PaleGoldenrod</string>\r\n" +
            "  <string>PaleGreen</string>\r\n  <string>PaleTurquoise</string>\r\n  <string>PaleVi" +
            "oletRed</string>\r\n  <string>PapayaWhip</string>\r\n  <string>PeachPuff</string>\r\n " +
            " <string>Peru</string>\r\n  <string>Pink</string>\r\n  <string>Plum</string>\r\n  <str" +
            "ing>PowderBlue</string>\r\n  <string>RosyBrown</string>\r\n  <string>RoyalBlue</stri" +
            "ng>\r\n  <string>SaddleBrown</string>\r\n  <string>Salmon</string>\r\n  <string>SandyB" +
            "rown</string>\r\n  <string>SeaGreen</string>\r\n  <string>SeaShell</string>\r\n  <stri" +
            "ng>Sienna</string>\r\n  <string>Silver</string>\r\n  <string>SkyBlue</string>\r\n  <st" +
            "ring>SlateBlue</string>\r\n  <string>SlateGray</string>\r\n  <string>Snow</string>\r\n" +
            "  <string>SpringGreen</string>\r\n  <string>SteelBlue</string>\r\n  <string>Tan</str" +
            "ing>\r\n  <string>Teal</string>\r\n  <string>Thistle</string>\r\n  <string>Tomato</str" +
            "ing>\r\n  <string>Turquoise</string>\r\n  <string>Violet</string>\r\n  <string>Wheat</" +
            "string>\r\n  <string>WhiteSmoke</string>\r\n  <string>Yellow</string>\r\n  <string>Yel" +
            "lowGreen</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesColors"]));
            }
            set {
                this["SeriesColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1</string>\r\n  <string>2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesWidth"]));
            }
            set {
                this["SeriesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsgsSiteNumber {
            get {
                return ((string)(this["UsgsSiteNumber"]));
            }
            set {
                this["UsgsSiteNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pal af")]
        public string HydrometInput {
            get {
                return ((string)(this["HydrometInput"]));
            }
            set {
                this["HydrometInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1989-10-01")]
        public global::System.DateTime HydrometT1 {
            get {
                return ((global::System.DateTime)(this["HydrometT1"]));
            }
            set {
                this["HydrometT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heii_quaf")]
        public string SumVolumeSiteName {
            get {
                return ((string)(this["SumVolumeSiteName"]));
            }
            set {
                this["SumVolumeSiteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:timeseries")]
        public string ServerDatabase {
            get {
                return ((string)(this["ServerDatabase"]));
            }
            set {
                this["ServerDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ibr1gcpdb004:Pisces     #sqlserver</string>
  <string>lrgs1.pn.usbr.gov:timeseries   #postgresql</string>
  <string>127.0.0.1:timeseries    #mysql</string>
  <string>127.0.0.1:timeseries   #postgresql</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabaseList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseList"]));
            }
            set {
                this["DatabaseList"] = value;
            }
        }
    }
}
