//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamation.TimeSeries.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1977 2001 2005")]
        public string UserWaterYears {
            get {
                return ((string)(this["UserWaterYears"]));
            }
            set {
                this["UserWaterYears"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <str" +
            "ing>Red</string>\n  <string>Green</string>\n  <string>Blue</string>\n  <string>Blac" +
            "k</string>\n  <string>Orange</string>\n  <string>Aquamarine</string>\n  <string>Bei" +
            "ge</string>\n  <string>DarkGreen</string>\n  <string>Purple</string>\n  <string>Aqu" +
            "a</string>\n  <string>Bisque</string>\n  <string>BlanchedAlmond</string>\n  <string" +
            ">BlueViolet</string>\n  <string>Brown</string>\n  <string>BurlyWood</string>\n  <st" +
            "ring>CadetBlue</string>\n  <string>Chartreuse</string>\n  <string>Chocolate</strin" +
            "g>\n  <string>Coral</string>\n  <string>CornflowerBlue</string>\n  <string>Cornsilk" +
            "</string>\n  <string>Crimson</string>\n  <string>Cyan</string>\n  <string>DarkBlue<" +
            "/string>\n  <string>DarkCyan</string>\n  <string>DarkGoldenrod</string>\n  <string>" +
            "DarkGray</string>\n  <string>DarkKhaki</string>\n  <string>DarkMagenta</string>\n  " +
            "<string>AntiqueWhite</string>\n  <string>DarkOliveGreen</string>\n  <string>DarkOr" +
            "ange</string>\n  <string>DarkOrchid</string>\n  <string>DarkRed</string>\n  <string" +
            ">DarkSalmon</string>\n  <string>DarkSeaGreen</string>\n  <string>DarkSlateBlue</st" +
            "ring>\n  <string>DarkSlateGray</string>\n  <string>DarkTurquoise</string>\n  <strin" +
            "g>DarkViolet</string>\n  <string>DeepPink</string>\n  <string>DeepSkyBlue</string>" +
            "\n  <string>DimGray</string>\n  <string>DodgerBlue</string>\n  <string>Firebrick</s" +
            "tring>\n  <string>FloralWhite</string>\n  <string>ForestGreen</string>\n  <string>F" +
            "uchsia</string>\n  <string>Gainsboro</string>\n  <string>GhostWhite</string>\n  <st" +
            "ring>Gold</string>\n  <string>Goldenrod</string>\n  <string>Gray</string>\n  <strin" +
            "g>Green</string>\n  <string>GreenYellow</string>\n  <string>Honeydew</string>\n  <s" +
            "tring>HotPink</string>\n  <string>IndianRed</string>\n  <string>Indigo</string>\n  " +
            "<string>Ivory</string>\n  <string>Khaki</string>\n  <string>Lavender</string>\n  <s" +
            "tring>LavenderBlush</string>\n  <string>LawnGreen</string>\n  <string>LemonChiffon" +
            "</string>\n  <string>LightBlue</string>\n  <string>LightCoral</string>\n  <string>L" +
            "ightCyan</string>\n  <string>LightGoldenrodYellow</string>\n  <string>LightGray</s" +
            "tring>\n  <string>LightGreen</string>\n  <string>LightPink</string>\n  <string>Ligh" +
            "tSalmon</string>\n  <string>LightSeaGreen</string>\n  <string>LightSkyBlue</string" +
            ">\n  <string>LightSlateGray</string>\n  <string>LightSteelBlue</string>\n  <string>" +
            "LightYellow</string>\n  <string>Lime</string>\n  <string>LimeGreen</string>\n  <str" +
            "ing>Linen</string>\n  <string>Magenta</string>\n  <string>Maroon</string>\n  <strin" +
            "g>MediumAquamarine</string>\n  <string>MediumBlue</string>\n  <string>MediumOrchid" +
            "</string>\n  <string>MediumPurple</string>\n  <string>MediumSeaGreen</string>\n  <s" +
            "tring>MediumSlateBlue</string>\n  <string>MediumSpringGreen</string>\n  <string>Me" +
            "diumTurquoise</string>\n  <string>MediumVioletRed</string>\n  <string>MidnightBlue" +
            "</string>\n  <string>MintCream</string>\n  <string>MistyRose</string>\n  <string>Mo" +
            "ccasin</string>\n  <string>NavajoWhite</string>\n  <string>Navy</string>\n  <string" +
            ">OldLace</string>\n  <string>Olive</string>\n  <string>OliveDrab</string>\n  <strin" +
            "g>OrangeRed</string>\n  <string>Orchid</string>\n  <string>PaleGoldenrod</string>\n" +
            "  <string>PaleGreen</string>\n  <string>PaleTurquoise</string>\n  <string>PaleViol" +
            "etRed</string>\n  <string>PapayaWhip</string>\n  <string>PeachPuff</string>\n  <str" +
            "ing>Peru</string>\n  <string>Pink</string>\n  <string>Plum</string>\n  <string>Powd" +
            "erBlue</string>\n  <string>RosyBrown</string>\n  <string>RoyalBlue</string>\n  <str" +
            "ing>SaddleBrown</string>\n  <string>Salmon</string>\n  <string>SandyBrown</string>" +
            "\n  <string>SeaGreen</string>\n  <string>SeaShell</string>\n  <string>Sienna</strin" +
            "g>\n  <string>Silver</string>\n  <string>SkyBlue</string>\n  <string>SlateBlue</str" +
            "ing>\n  <string>SlateGray</string>\n  <string>Snow</string>\n  <string>SpringGreen<" +
            "/string>\n  <string>SteelBlue</string>\n  <string>Tan</string>\n  <string>Teal</str" +
            "ing>\n  <string>Thistle</string>\n  <string>Tomato</string>\n  <string>Turquoise</s" +
            "tring>\n  <string>Violet</string>\n  <string>Wheat</string>\n  <string>WhiteSmoke</" +
            "string>\n  <string>Yellow</string>\n  <string>YellowGreen</string>\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection SeriesColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesColors"]));
            }
            set {
                this["SeriesColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <str" +
            "ing>1</string>\n  <string>2</string>\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesWidth"]));
            }
            set {
                this["SeriesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsgsSiteNumber {
            get {
                return ((string)(this["UsgsSiteNumber"]));
            }
            set {
                this["UsgsSiteNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pal af")]
        public string HydrometInput {
            get {
                return ((string)(this["HydrometInput"]));
            }
            set {
                this["HydrometInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1989-10-01")]
        public global::System.DateTime HydrometT1 {
            get {
                return ((global::System.DateTime)(this["HydrometT1"]));
            }
            set {
                this["HydrometT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heii_quaf")]
        public string SumVolumeSiteName {
            get {
                return ((string)(this["SumVolumeSiteName"]));
            }
            set {
                this["SumVolumeSiteName"] = value;
            }
        }
    }
}
