//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamation.TimeSeries.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1977 2001 2005")]
        public string UserWaterYears {
            get {
                return ((string)(this["UserWaterYears"]));
            }
            set {
                this["UserWaterYears"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Red</string>\r\n  <string>Green</string>\r\n  <string>Blue</string>\r\n  <string" +
            ">Black</string>\r\n  <string>Orange</string>\r\n  <string>Aquamarine</string>\r\n  <st" +
            "ring>DarkGreen</string>\r\n  <string>Purple</string>\r\n  <string>Aqua</string>\r\n  <" +
            "string>BlueViolet</string>\r\n  <string>Brown</string>\r\n  <string>BurlyWood</strin" +
            "g>\r\n  <string>CadetBlue</string>\r\n  <string>Chartreuse</string>\r\n  <string>Choco" +
            "late</string>\r\n  <string>Coral</string>\r\n  <string>CornflowerBlue</string>\r\n  <s" +
            "tring>Crimson</string>\r\n  <string>Cyan</string>\r\n  <string>DarkBlue</string>\r\n  " +
            "<string>DarkCyan</string>\r\n  <string>DarkGoldenrod</string>\r\n  <string>DarkGray<" +
            "/string>\r\n  <string>DarkKhaki</string>\r\n  <string>DarkMagenta</string>\r\n  <strin" +
            "g>DarkOliveGreen</string>\r\n  <string>DarkOrange</string>\r\n  <string>DarkOrchid</" +
            "string>\r\n  <string>DarkRed</string>\r\n  <string>DarkSalmon</string>\r\n  <string>Da" +
            "rkSeaGreen</string>\r\n  <string>DarkSlateBlue</string>\r\n  <string>DarkSlateGray</" +
            "string>\r\n  <string>DarkTurquoise</string>\r\n  <string>DarkViolet</string>\r\n  <str" +
            "ing>DeepPink</string>\r\n  <string>DeepSkyBlue</string>\r\n  <string>DimGray</string" +
            ">\r\n  <string>DodgerBlue</string>\r\n  <string>Firebrick</string>\r\n  <string>Forest" +
            "Green</string>\r\n  <string>Fuchsia</string>\r\n  <string>Gainsboro</string>\r\n  <str" +
            "ing>Gold</string>\r\n  <string>Goldenrod</string>\r\n  <string>Gray</string>\r\n  <str" +
            "ing>Green</string>\r\n  <string>GreenYellow</string>\r\n  <string>HotPink</string>\r\n" +
            "  <string>IndianRed</string>\r\n  <string>Indigo</string>\r\n  <string>Khaki</string" +
            ">\r\n  <string>Lavender</string>\r\n  <string>LavenderBlush</string>\r\n  <string>Lawn" +
            "Green</string>\r\n  <string>LightBlue</string>\r\n  <string>LightCoral</string>\r\n  <" +
            "string>LightCyan</string>\r\n  <string>LightGray</string>\r\n  <string>LightGreen</s" +
            "tring>\r\n  <string>LightPink</string>\r\n  <string>LightSalmon</string>\r\n  <string>" +
            "LightSeaGreen</string>\r\n  <string>LightSkyBlue</string>\r\n  <string>LightSlateGra" +
            "y</string>\r\n  <string>LightSteelBlue</string>\r\n  <string>Lime</string>\r\n  <strin" +
            "g>LimeGreen</string>\r\n  <string>Magenta</string>\r\n  <string>Maroon</string>\r\n  <" +
            "string>MediumAquamarine</string>\r\n  <string>MediumBlue</string>\r\n  <string>Mediu" +
            "mOrchid</string>\r\n  <string>MediumPurple</string>\r\n  <string>MediumSeaGreen</str" +
            "ing>\r\n  <string>MediumSlateBlue</string>\r\n  <string>MediumSpringGreen</string>\r\n" +
            "  <string>MediumTurquoise</string>\r\n  <string>MediumVioletRed</string>\r\n  <strin" +
            "g>MidnightBlue</string>\r\n  <string>MistyRose</string>\r\n  <string>Moccasin</strin" +
            "g>\r\n  <string>NavajoWhite</string>\r\n  <string>Navy</string>\r\n  <string>Olive</st" +
            "ring>\r\n  <string>OliveDrab</string>\r\n  <string>OrangeRed</string>\r\n  <string>Orc" +
            "hid</string>\r\n  <string>PaleGoldenrod</string>\r\n  <string>PaleGreen</string>\r\n  " +
            "<string>PaleTurquoise</string>\r\n  <string>PaleVioletRed</string>\r\n  <string>Papa" +
            "yaWhip</string>\r\n  <string>PeachPuff</string>\r\n  <string>Peru</string>\r\n  <strin" +
            "g>Pink</string>\r\n  <string>Plum</string>\r\n  <string>PowderBlue</string>\r\n  <stri" +
            "ng>RosyBrown</string>\r\n  <string>RoyalBlue</string>\r\n  <string>SaddleBrown</stri" +
            "ng>\r\n  <string>Salmon</string>\r\n  <string>SandyBrown</string>\r\n  <string>SeaGree" +
            "n</string>\r\n  <string>Sienna</string>\r\n  <string>Silver</string>\r\n  <string>SkyB" +
            "lue</string>\r\n  <string>SlateBlue</string>\r\n  <string>SlateGray</string>\r\n  <str" +
            "ing>SpringGreen</string>\r\n  <string>SteelBlue</string>\r\n  <string>Tan</string>\r\n" +
            "  <string>Teal</string>\r\n  <string>Thistle</string>\r\n  <string>Tomato</string>\r\n" +
            "  <string>Turquoise</string>\r\n  <string>Violet</string>\r\n  <string>Wheat</string" +
            ">\r\n  <string>Yellow</string>\r\n  <string>YellowGreen</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesColors"]));
            }
            set {
                this["SeriesColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1</string>\r\n  <string>2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesWidth"]));
            }
            set {
                this["SeriesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsgsSiteNumber {
            get {
                return ((string)(this["UsgsSiteNumber"]));
            }
            set {
                this["UsgsSiteNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pal af")]
        public string HydrometInput {
            get {
                return ((string)(this["HydrometInput"]));
            }
            set {
                this["HydrometInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1989-10-01")]
        public global::System.DateTime HydrometT1 {
            get {
                return ((global::System.DateTime)(this["HydrometT1"]));
            }
            set {
                this["HydrometT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("heii_quaf")]
        public string SumVolumeSiteName {
            get {
                return ((string)(this["SumVolumeSiteName"]));
            }
            set {
                this["SumVolumeSiteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:timeseries")]
        public string ServerDatabase {
            get {
                return ((string)(this["ServerDatabase"]));
            }
            set {
                this["ServerDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ibr1gcpdb004:Pisces     #sqlserver</string>
  <string>lrgs1.pn.usbr.gov:timeseries   #postgresql</string>
  <string>127.0.0.1:timeseries    #mysql</string>
  <string>127.0.0.1:timeseries   #postgresql</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabaseList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseList"]));
            }
            set {
                this["DatabaseList"] = value;
            }
        }
    }
}
