//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamation.TimeSeries.Graphing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Red</string>\r\n  <string>Green</string>\r\n  <string>Blue</string>\r\n  <string" +
            ">Black</string>\r\n  <string>Orange</string>\r\n  <string>Aquamarine</string>\r\n  <st" +
            "ring>Beige</string>\r\n  <string>DarkGreen</string>\r\n  <string>Purple</string>\r\n  " +
            "<string>Aqua</string>\r\n  <string>Bisque</string>\r\n  <string>BlanchedAlmond</stri" +
            "ng>\r\n  <string>BlueViolet</string>\r\n  <string>Brown</string>\r\n  <string>BurlyWoo" +
            "d</string>\r\n  <string>CadetBlue</string>\r\n  <string>Chartreuse</string>\r\n  <stri" +
            "ng>Chocolate</string>\r\n  <string>Coral</string>\r\n  <string>CornflowerBlue</strin" +
            "g>\r\n  <string>Cornsilk</string>\r\n  <string>Crimson</string>\r\n  <string>Cyan</str" +
            "ing>\r\n  <string>DarkBlue</string>\r\n  <string>DarkCyan</string>\r\n  <string>DarkGo" +
            "ldenrod</string>\r\n  <string>DarkGray</string>\r\n  <string>DarkKhaki</string>\r\n  <" +
            "string>DarkMagenta</string>\r\n  <string>DarkOliveGreen</string>\r\n  <string>DarkOrange" +
            "</string>\r\n  <string>DarkOrchid</string>\r\n  <string>DarkRed</string>\r\n  <string>Dark" + 
            "Salmon</string>\r\n  <string>DarkSeaGreen</string>\r\n  <string>DarkSlateBlue</string>\r\n  " + 
            "<string>DarkSlateGray</string>\r\n  <string>DarkTurquoise</string>\r\n  <string>DarkViolet" + 
            "</string>\r\n  <string>DeepPink</string>\r\n  <string>DeepSkyBlue</string>\r\n  <string>Dim" + 
            "Gray</string>\r\n  <string>DodgerBlue</string>\r\n  <string>Firebrick</string>\r\n  " + 
            "<string>ForestGreen</string>\r\n  <string>Fuchsia</string>\r\n  <string>Gainsboro</string>\r\n  " + 
            "<string>Gold</string>\r\n  <string>Goldenrod</string>\r\n  <string>Gray</string>\r\n  " + 
            "<string>Green</string>\r\n  <string>GreenYellow</string>\r\n  <string>Honeydew</string>\r\n  " + 
            "<string>HotPink</string>\r\n  <string>IndianRed</string>\r\n  <string>Indigo</string>\r\n  " + 
            "<string>Ivory</string>\r\n  <string>Khaki</string>\r\n  <string>Lavender</string>\r\n  <string>LavenderBl" +
            "ush</string>\r\n  <string>LawnGreen</string>\r\n  <string>LemonChiffon</string>\r\n  <" +
            "string>LightBlue</string>\r\n  <string>LightCoral</string>\r\n  <string>LightCyan</s" +
            "tring>\r\n  <string>LightGoldenrodYellow</string>\r\n  <string>LightGray</string>\r\n " +
            " <string>LightGreen</string>\r\n  <string>LightPink</string>\r\n  <string>LightSalmo" +
            "n</string>\r\n  <string>LightSeaGreen</string>\r\n  <string>LightSkyBlue</string>\r\n " +
            " <string>LightSlateGray</string>\r\n  <string>LightSteelBlue</string>\r\n  <string>L" +
            "ightYellow</string>\r\n  <string>Lime</string>\r\n  <string>LimeGreen</string>\r\n  <s" +
            "tring>Linen</string>\r\n  <string>Magenta</string>\r\n  <string>Maroon</string>\r\n  <" +
            "string>MediumAquamarine</string>\r\n  <string>MediumBlue</string>\r\n  <string>Mediu" +
            "mOrchid</string>\r\n  <string>MediumPurple</string>\r\n  <string>MediumSeaGreen</str" +
            "ing>\r\n  <string>MediumSlateBlue</string>\r\n  <string>MediumSpringGreen</string>\r\n" +
            "  <string>MediumTurquoise</string>\r\n  <string>MediumVioletRed</string>\r\n  <strin" +
            "g>MidnightBlue</string>\r\n  <string>MintCream</string>\r\n  <string>MistyRose</stri" +
            "ng>\r\n  <string>Moccasin</string>\r\n  <string>Navy</string>\r\n  <string>OldLace</string>\r\n  " + 
            "<string>Olive</string>\r\n  <string>OliveDrab</string>\r\n  <string>OrangeRed</string>\r\n  " + 
            "<string>Orchid</string>\r\n  <string>PaleGoldenrod</string>\r\n  <string>PaleGreen</string>\r\n  " + 
            "<string>PaleTurquoise</string>\r\n  <string>PaleVioletRed</string>\r\n  <string>PapayaWhip</string>\r\n  " + 
            "<string>PeachPuff</string>\r\n  <string>Peru</string>\r\n  <string>Pink</string>\r\n  <st" +
            "ring>Plum</string>\r\n  <string>PowderBlue</string>\r\n  <string>RosyBrown</string>\r" +
            "\n  <string>RoyalBlue</string>\r\n  <string>SaddleBrown</string>\r\n  <string>Salmon<" +
            "/string>\r\n  <string>SandyBrown</string>\r\n  <string>SeaGreen</string>\r\n  <string>" +
            "SeaShell</string>\r\n  <string>Sienna</string>\r\n  <string>Silver</string>\r\n  <stri" +
            "ng>SkyBlue</string>\r\n  <string>SlateBlue</string>\r\n  <string>SlateGray</string>\r" +
            "\n  <string>Snow</string>\r\n  <string>SpringGreen</string>\r\n  <string>SteelBlue</s" +
            "tring>\r\n  <string>Tan</string>\r\n  <string>Teal</string>\r\n  <string>Thistle</stri" +
            "ng>\r\n  <string>Tomato</string>\r\n  <string>Turquoise</string>\r\n  <string>Violet</" +
            "string>\r\n  <string>Wheat</string>\r\n  <string>Yell" +
            "ow</string>\r\n  <string>YellowGreen</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesColors"]));
            }
            set {
                this["SeriesColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1</string>\r\n  <string>2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SeriesWidth {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SeriesWidth"]));
            }
            set {
                this["SeriesWidth"] = value;
            }
        }
    }
}
