//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamation.NetTimeSeries.corefx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reclamation.NetTimeSeries.corefx.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataRowComparer does not work with DataRows that have been deleted since it only compares current values..
        /// </summary>
        internal static string DataSetLinq_CannotCompareDeletedRow {
            get {
                return ResourceManager.GetString("DataSetLinq_CannotCompareDeletedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source contains a deleted DataRow that cannot be copied to the DataTable..
        /// </summary>
        internal static string DataSetLinq_CannotLoadDeletedRow {
            get {
                return ResourceManager.GetString("DataSetLinq_CannotLoadDeletedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source contains a detached DataRow that cannot be copied to the DataTable..
        /// </summary>
        internal static string DataSetLinq_CannotLoadDetachedRow {
            get {
                return ResourceManager.GetString("DataSetLinq_CannotLoadDetachedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source contains no DataRows..
        /// </summary>
        internal static string DataSetLinq_EmptyDataRowSource {
            get {
                return ResourceManager.GetString("DataSetLinq_EmptyDataRowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} enumeration value, {1}, is not valid..
        /// </summary>
        internal static string DataSetLinq_InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("DataSetLinq_InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast DBNull. Value to type &apos;{0}&apos;. Please use a nullable type..
        /// </summary>
        internal static string DataSetLinq_NonNullableCast {
            get {
                return ResourceManager.GetString("DataSetLinq_NonNullableCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source contains a DataRow reference that is null..
        /// </summary>
        internal static string DataSetLinq_NullDataRow {
            get {
                return ResourceManager.GetString("DataSetLinq_NullDataRow", resourceCulture);
            }
        }
    }
}
